<?php

/**
 * @file
 * Hook implementations for this module.
 */

module_load_include('inc', 'webform', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function webform_postcodeapi_theme() {
  return [
    'webform_postcodeapi' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for webform_postcodeapi composite templates.
 *
 * Default template: webform-postcodeapi.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_postcodeapi(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}
