webform_postcode_austria.settings:
  type: config_object
  mapping:
    postcodenlapi_key:
      label: 'Postcode AT API URL'
      type: string
    postcodenlapi_url:
      label: 'Postcode AT API Key'
      type: uri
